[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  PUBLIC_URL = "/"
  SKIP_PREFLIGHT_CHECK = "true"
  
  # Supabase Environment Variables - These should be set in Netlify dashboard
  REACT_APP_SUPABASE_URL = "https://ivqlwwzqaevvloloofjf.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2cWx3d3pxYWV2dmxvbG9vZmpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTU2NjIsImV4cCI6MjA2MzgzMTY2Mn0.jO7Gj14immdvAtVx4f3whb-2AWddpyQj-AayO-YIrEE"

[build.processing]
  skip_processing = true

# Handle client-side routing - redirect all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data: https:; connect-src 'self' https:;"

# Cache static assets for 1 year (recommended for production)
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
